on:
  push:
    branches:
      - main

name: '[Prod] Deploy to Cloud Run'
jobs:
  cloudrun:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: 'access_token'
        credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'

    - id: 'build'
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: europe-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}

    - id: 'push'
      name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: app
        push: true
        tags: europe-docker.pkg.dev/api-front-dashbord/production/aff:latest

    - id: 'deploy_gamingaffiliates'
      name: deploy gamingaffiliates
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'gamingaffiliates-prod'
        image: 'europe-docker.pkg.dev/api-front-dashbord/production/aff:latest'
        labels:
          env=prod
        project_id: api-front-dashbord
        region: europe-west1
        secrets: |
          DATABASE_URL=PROD_DATABASE_URL:latest
          SHADOW_DATABASE_URL=PROD_SHADOW_DATABASE_URL:latest
          LEGACY_PHP_ACCESS_TOKEN=PROD_LEGACY_PHP_ACCESS_TOKEN:latest
          NEXTAUTH_SECRET=PROD_NEXTAUTH_SECRET:latest
        env_vars: |
          LEGACY_PHP_API_URL=https://affiliate-com.netlify.app/api/document-upload-just-log
          NEXTAUTH_URL=http://localhost:3001
        flags: |
          --allow-unauthenticated
          --vpc-connector=production-serverless-vp 
          --vpc-egress=all-traffic
          --port=3000

    - id: 'deploy_best-brokers-partners'
      name: deploy best-brokers-partners
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'best-brokers-partners-prod'
        image: 'europe-docker.pkg.dev/api-front-dashbord/production/aff:latest'
        labels:
          env=prod
        project_id: api-front-dashbord
        region: europe-west1
        secrets: |
          DATABASE_URL=PROD_DATABASE_URL:latest
          SHADOW_DATABASE_URL=PROD_SHADOW_DATABASE_URL:latest
          LEGACY_PHP_ACCESS_TOKEN=PROD_LEGACY_PHP_ACCESS_TOKEN:latest
          NEXTAUTH_SECRET=PROD_NEXTAUTH_SECRET:latest
        env_vars: |
          LEGACY_PHP_API_URL=https://affiliate-com.netlify.app/api/document-upload-just-log
          NEXTAUTH_URL=http://localhost:3001
        flags: |
          --allow-unauthenticated
          --vpc-connector=production-serverless-vp 
          --vpc-egress=all-traffic
          --port=3000